backend/models/Theme.php
<?php

namespace backend\models;

use hdmodules\content\models\Item;
use hdmodules\base\components\ActiveRecord;
use hdmodules\base\multilanguage\MultiLanguageBehavior;
use hdmodules\base\multilanguage\MultiLanguageTrait;

class Theme extends ActiveRecord {

    public $crop_info;

    public static function tableName() {
        return "theme";
    }

    public function rules()	{
        return [
            [['cropped_1','cropped_2','cropped_3'],'safe'],
        ];
    }

    public function attributeLabels() {
        return [
            "cropped_1" => "Cropped 1",
            "cropped_2" => "Cropped 2",
            "cropped_3" => "Cropped 3",
        ];
    }

}

backend/controllers/ThemeController.php
<?php
namespace backend\controllers;

use Yii;
use backend\models\GameThemeItem;
use hdmodules\content\controllers\ItemController;
use yii\widgets\ActiveForm;

class ThemeController extends ItemController
{
    public $viewPath = '@backend/views/theme';

    public function init()
    {
        $this->class_model = GameThemeItem::className();
        return parent::init();
    }
    
    public function actionEdit($id)
    {
        $class_model = $this->class_model;

        if(!($model = $class_model::findOne($id))){
            return $this->redirect(['/block/index']);
        }

        $model->loadTranslations_custom();

        if ($model->load(Yii::$app->request->post())) {
            if(Yii::$app->request->isAjax){
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
            else {
                if ($model->save()) {
                    $this->flash('success', Yii::t('content', 'Item updated'));
                    return $this->redirect([($model->block->controller_name ? $model->block->controller_name.'/edit' :'/content/item/edit'), 'id' => $model->primaryKey]);
                } else {
                    $this->flash('error', Yii::t('content', 'Update error. {0}', $model->formatErrors()));
                }
            }
        }

        return $this->render($this->viewPath.'/edit', [
            'model' => $model,
        ]);

    }
    
    public function actionClearAnimationImage($id)
    {
        $class_model = $this->class_model;

        $model = $class_model::findOne($id);

        if($model === null){
            $this->flash('error', Yii::t('content', 'Not found'));
        }
        elseif($model->attribute_1){
            $model->attribute_1 = '';
            if($model->save(false)){
                $this->flash('success', Yii::t('content', 'Image cleared'));
            } else {
                $this->flash('error', Yii::t('content', 'Update error. {0}', $model->formatErrors()));
            }
        }
        return $this->back();
    }
    
    public function actionCrop($id) {

        if(!($model = GameThemeItem::findOne($id))){
            return $this->redirect(['/block/index']);
        }

        if ($model->theme->load(Yii::$app->request->post())) {
            if($model->theme->cropped_1 && $model->theme->cropped_2 && $model->theme->cropped_3) {
                for($i = 1; $i <= 3; $i++) {
                    $imagename = pathinfo($model->{"image"},PATHINFO_FILENAME);
                    $extension = pathinfo($model->{"image"},PATHINFO_EXTENSION);
                    $path = Yii::getAlias("@frontend/web/uploads/theme/{$imagename}_$i.$extension");
                    if(!file_exists( Yii::getAlias("@frontend/web/uploads/theme"))) {
                        mkdir( Yii::getAlias("@frontend/web/uploads/theme"));
                    }
                    $data = base64_decode(preg_replace('#^data:image/\w+;base64,#i', '', $model->theme->{"cropped_$i"}));
                    file_put_contents($path,$data);
                    $model->theme->{"cropped_$i"} = str_replace(Yii::getAlias("@frontend/web"),'',$path);
                }
            }
            if ($model->theme->save()){
                $this->flash('success', Yii::t('theme', 'Theme updated'));
                return $this->redirect([($model->block->controller_name ? $model->block->controller_name.'/edit' :'/content/item/edit'), 'id' => $model->primaryKey]);
            } else {
                $this->flash('error', Yii::t('theme', 'Update error. {0}', $model->formatErrors()));
                return $this->refresh();
            }
        }
        return $this->render('crop',['model' => $model, 'id' => $id]);
    }


}

backend/views/theme/_form.php
<?php
use hdmodules\base\helpers\Image;
use hdmodules\base\widgets\SeoForm;
use hdmodules\base\widgets\DateTimePicker;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

use hdmodules\base\multilanguage\input_widget\MultiLanguageActiveField;
use hdmodules\base\widgets\RedactorMultiLanguageInput;
use kartik\widgets\Select2;

$module = $this->context->module->id;
?>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">

            <div class="x_title">
                <h2><?= Yii::t('content', 'Form') ?> <small><?= Yii::t('content', 'create theme') ?></small></h2>
                <ul class="nav navbar-right">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>

            <div class="x_content">

                <?php $form = ActiveForm::begin([
                    'enableAjaxValidation' => true,
                    'validateOnSubmit' => true,
                    'options' => ['enctype' => 'multipart/form-data', 'class' => 'model-form']
                ]); ?>

                    <?= $form->field($model, 'title')->label('Name') ?>

                    <div style="margin: 30px 0 30px 0">
                        <?php if($model->image) : ?>
                            <img src="<?= Image::thumb($model->image, 240) ?>">
                            <a href="<?= Url::to(['/content/item/clear-image', 'id' => $model->primaryKey]) ?>" class="text-danger confirm-delete" title="<?= Yii::t('content', 'Clear image')?>"><?= Yii::t('content', 'Clear image')?></a>
                        <?php endif; ?>

                        <?= $form->field($model, 'image')->fileInput() ?>
                    </div>
                
                    <div style="margin: 30px 0 30px 0">
                        <?php if($model->attribute_1) : ?>
                            <img src="<?= $model->attribute_1 ?>">
                            <a href="<?= Url::to(['theme/clear-animation-image', 'id' => $model->primaryKey]) ?>" class="text-danger confirm-delete" title="<?= Yii::t('content', 'Clear image')?>"><?= Yii::t('content', 'Clear image')?></a>
                        <?php endif; ?>

                        <?= $form->field($model, 'attribute_1')->fileInput()->label('Gif animation') ?>
                    </div>
                
                    <?= $form->field($model, 'slug') ?>
                    
                    <?= $form->field($model, 'attribute_3')->checkbox() ?>
                
                    <?php if(Yii::$app->controller->action->id == 'create' || (Yii::$app->controller->action->id == 'edit')) : ?>
                        <?= SeoForm::widget(['model' => $model]) ?>
                    <?php endif; ?>

                    <div class="ln_solid"></div>

                    <?= Html::submitButton(Yii::t('content', 'Save'), ['class' => 'btn btn-primary']) ?>

                <?php ActiveForm::end(); ?>

            </div>
        </div>
    </div>
</div>

backend/views/theme/_menu.php
<?php
use yii\helpers\Url;

$action = $this->context->action->id;

?>
<ul class="nav nav-pills">
    <?php if($action == 'index') : ?>
        <li><a href="<?= Url::to(['/content/block']) ?>"><i class="glyphicon glyphicon-chevron-left font-12"></i> <?= Yii::t('content', 'Blocks') ?></a></li>
    <?php endif; ?>
    <li <?= ($action == 'index') ? 'class="active"' : '' ?>><a href="<?= Url::to([($block->controller_name ? '/'.$block->controller_name : '/content/item') , 'id' => $block->primaryKey]) ?>"><?php if($action != 'index') echo '<i class="glyphicon glyphicon-chevron-left font-12"></i> ' ?><?= $block->title ?></a></li>
    <li <?= ($action == 'create') ? 'class="active"' : '' ?>><a href="<?= Url::to([($block->controller_name ? $block->controller_name.'/create' : '/content/item/create') , 'id' => $block->primaryKey]) ?>"><?= Yii::t('content', 'Add') ?></a></li>
</ul>
<br/>

backend/views/theme/_submenu.php
<?php
use yii\helpers\Url;

$action = $this->context->action->id;
$module = $this->context->module->id;
?>

<ul class="nav nav-tabs">
    <li <?= ($action === 'edit') ? 'class="active"' : '' ?>><a href="<?= Url::to([($model->block->controller_name ? $model->block->controller_name.'/edit' : '/'.$module.'/item/edit'), 'id' => $model->primaryKey]) ?>"><?= Yii::t('easyii/landing', 'Edit game') ?></a></li>
<!--    <li <?= ($action === 'crop') ? 'class="active"' : '' ?>><a href="<?= Url::to([($model->block->controller_name ? $model->block->controller_name.'/crop' : '/'.$module.'/item/crop'), 'id' => $model->primaryKey]) ?>"><span class="glyphicon glyphicon-crop"></span> <?= Yii::t('news', 'Crop image') ?></a></li>-->
</ul>
<br>

backend/views/theme/create.php
<?php
$this->title = Yii::t('content', 'Create theme');
?>
<?= $this->render('_menu', ['block' => $block]) ?>
<?= $this->render('_form', ['model' => $model]) ?>

backend/views/theme/crop.php
<?php
use hdmodules\base\cropbox\Cropbox;
use yii\widgets\ActiveForm;
use yii\helpers\Html;

$this->title = $model->title;

?>
<?= $this->render('_menu', ['block' => $model->block]) ?>
<?= $this->render('_submenu', ['model' => $model]) ?>


<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="x_panel">

			<div class="x_title">
				<h2><?= Yii::t('theme', 'Form') ?> <small><?= Yii::t('theme', 'Cropped images (230x230, 473.333333x230, 230x473.333333)') ?></small></h2>
				<ul class="nav navbar-right">
					<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
					</li>
				</ul>
				<div class="clearfix"></div>
			</div>

			<div class="x_content">
				<?php if($model->theme->{"cropped_1"} && $model->theme->{"cropped_2"} && $model->theme->{"cropped_3"}) { ?>
					<h2>Saved cropped images:</h2>
					<?php  for($i = 1; $i <= 3; $i++) { ?>
						<img src="<?= $model->theme->{"cropped_{$i}"} ?>"/>
					<?php } ?>
					<hr>
				<?php } ?>


				<?php if($model->image) { ?>

					<?php  $this->registerJs("

						$(document).ready(function () {
							var xhr = new XMLHttpRequest();
							xhr.open('GET', '". $model->image ."', true);
							xhr.responseType = 'blob';
							xhr.onload = function (e) {
								if (this.status == 200) {
									window.blob = new Blob([this.response], {type: '".image_type_to_mime_type(exif_imagetype($_SERVER['DOCUMENT_ROOT'] ."/frontend/web/". $model->image))."'});
									$('input[type=file]').trigger('change');
								}
							}
							xhr.send();
						
							var k = 0;
							$('.cropped').bind('DOMSubtreeModified', function () {
								if (k == 3) {
									$('#theme-cropped_1').val($('.img-thumbnail:eq(0)').prop('src'));
									$('#theme-cropped_2').val($('.img-thumbnail:eq(1)').prop('src'));
									$('#theme-cropped_3').val($('.img-thumbnail:eq(2)').prop('src'));
								}
								k++;
							});
						});
					
					", \yii\web\View::POS_READY); ?>


					<?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

					<?= $form->field($model, 'image')->widget(Cropbox::className(), [
						'attributeCropInfo' => 'crop_info',
						'pluginOptions'=> [
							'variants'=>[
								[
									'width'=> 230,
									'height'=> 230
								],
								[
									'width'=> 473.333333,
									'height'=> 230
								],
								[
									'width'=> 230,
									'height'=> 473.333333
								]
							]
						]
					])->label('Cropped images (230x230, 473.333333x230, 230x473.333333)') ?>

					<?= $form->field($model->theme, 'cropped_1')->hiddenInput()->label(false) ?>
					<?= $form->field($model->theme, 'cropped_2')->hiddenInput()->label(false) ?>
					<?= $form->field($model->theme, 'cropped_3')->hiddenInput()->label(false) ?>

					<div class="ln_solid"></div>

					<?= Html::submitButton(Yii::t('easyii', 'Save'), ['class' => 'btn btn-primary']) ?>

					<?php  ActiveForm::end();?>

				<?php } else { ?>

					<p><?= \Yii::t('theme', 'No image found. You first need to upload an image.') ?></p>

				<?php } ?>
			</div>
		</div>
	</div>
</div>

backend/views/theme/edit.php
<?php
$this->title = $model->title;
?>
<?= $this->render('_menu', ['block' => $model->block]) ?>

<?= $this->render('_submenu', ['model' => $model]) ?>

<?= $this->render('_form', ['model' => $model]) ?>